create extension if not exists pgcrypto;
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text not null,created_at timestamptz default now());
create table public.groups(id uuid primary key default gen_random_uuid(),name text not null,invite_code text unique not null default upper(substr(replace(gen_random_uuid()::text,'-',''),1,8)),owner_id uuid not null references auth.users(id),created_at timestamptz default now());
create table public.group_members(group_id uuid references public.groups(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,joined_at timestamptz default now(),primary key(group_id,user_id));
create table public.messages(id bigint generated always as identity primary key,group_id uuid references public.groups(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,content text not null,created_at timestamptz default now());
create index messages_group_time on public.messages(group_id,created_at);
alter table public.profiles enable row level security; alter table public.groups enable row level security; alter table public.group_members enable row level security; alter table public.messages enable row level security;
create or replace function public.is_group_member(gid uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.group_members where group_id=gid and user_id=auth.uid())$$;
create policy "profiles read" on public.profiles for select to authenticated using(true);
create policy "profile own insert" on public.profiles for insert to authenticated with check(id=auth.uid());
create policy "groups read" on public.groups for select to authenticated using(public.is_group_member(id) or owner_id=auth.uid());
create policy "members read" on public.group_members for select to authenticated using(user_id=auth.uid() or public.is_group_member(group_id));
create policy "messages read" on public.messages for select to authenticated using(public.is_group_member(group_id));
create policy "messages insert" on public.messages for insert to authenticated with check(user_id=auth.uid() and public.is_group_member(group_id));
create policy "messages delete own" on public.messages for delete to authenticated using(user_id=auth.uid());
create or replace function public.create_chat_group(group_name text) returns uuid language plpgsql security definer set search_path=public as $$declare gid uuid;begin insert into public.groups(name,owner_id) values(group_name,auth.uid()) returning id into gid;insert into public.group_members(group_id,user_id) values(gid,auth.uid());return gid;end$$;
grant execute on function public.create_chat_group(text) to authenticated;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,username) values(new.id,coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1)));return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
alter publication supabase_realtime add table public.messages;